dist: trusty

language: rust

rust:
  - stable

sudo: required

before_install:
  - set -e
  - rustup self update

install:
- wget https://github.com/jedisct1/libsodium/releases/download/1.0.15/libsodium-1.0.15.tar.gz
- tar xvfz libsodium-1.0.15.tar.gz
- cd libsodium-1.0.15 && ./configure --prefix=$HOME/installed_libsodium && make && make install &&
  cd ..
- export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
- export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH

before_script:
  - cargo install cargo-travis && export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
  - cargo doc --verbose

after_script:
  - set +e

after_success:
  - cargo coveralls

notifications:
  email:
    on_success: never

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - diffutils
      - make
      - m4
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
    sources:
      - kalakris-cmake
