dist: trusty

language: rust

rust:
  - stable

sudo: required

before_install:
  - set -e
  - rustup self update
  - sudo apt-get install libsodium-dev

before_script:
  - cargo install cargo-travis && export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
  - cargo doc --verbose

after_script:
  - set +e

after_success:
  - cargo coveralls --tests

notifications:
  email:
    on_success: never

addons:
  apt:
    update: true
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - diffutils
      - make
      - m4
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
    sources:
      - kalakris-cmake
