dist: trusty

sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failure:
    - rust: nightly

addons:
  apt:
    packages:
      - libssl-dev

cache: cargo

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

before_install:
  - set -e
  - rustup self update

install:
- wget https://github.com/jedisct1/libsodium/releases/download/1.0.15/libsodium-1.0.15.tar.gz
- tar xvfz libsodium-1.0.15.tar.gz
- cd libsodium-1.0.15 && ./configure --prefix=$HOME/installed_libsodium && make && make install &&
  cd ..
- export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
- export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH

script:
  - cargo clean
  - cargo build --verbose
  - cargo test --verbose

after_script:
  - set +e

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi

notifications:
  email:
    on_success: never