[package]
name = "mitrid_core"
version = "0.1.0"
authors = ["Christian Nyumbayire <chritchens@gmail.com>"]

[dependencies]
futures = "^0.1"
serde = "^1"
serde_derive = "^1"
serde_json = "^1"
serde_cbor = "^0.9"
hex = "^0.3"
regex = "^1"